version: '3.3'

RUN:
 pip install passlib

services:
  db:
    image: postgres:14.13-alpine3.20
    environment:
    - POSTGRES_USER=User
    - POSTGRES_PASSWORD=Zaq123edc
    - PGDATA=/var/lib/postgresql/data/pgdata
    - POSTGRES_DB=t_db
    - DATABASE_URL=postgresql://stud:Zaq123edc@127.0.0.1:47292/t_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: