version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - postgres
      - mongo
      - redis
    environment:
      - DATABASE_URL=postgresql://stud:Zaq123edc@127.0.0.1:47292/t_db
      - MONGO_URL=mongodb://localhost:27017
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    command: bash -c "python /app/LW4.py && uvicorn main:app --host 0.0.0.0 --port 8000"

  postgres:
    image: postgres:14.13-alpine3.20
    container_name: postgres
    environment:
      POSTGRES_USER: stud
      POSTGRES_PASSWORD: Zaq123edc
      POSTGRES_DB: t_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  mongo:
    image: mongodb/mongodb-community-server:5.0.19-ubuntu2004
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: mongod --bind_ip_all

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  mongo_data:
